[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"

# Production environment variables (these should be set in Netlify dashboard)
# [context.production.environment]
#   DATABASE_URL = "postgresql://username:password@host.neon.tech/dbname?sslmode=require"

# Redirect rules for API routes to serverless functions
[[redirects]]
  from = "/api/wallet"
  to = "/.netlify/functions/wallet"
  status = 200

[[redirects]]
  from = "/api/admin/inject"
  to = "/.netlify/functions/admin-inject"
  status = 200

[[redirects]]
  from = "/api/trending"
  to = "/.netlify/functions/trending"
  status = 200

[[redirects]]
  from = "/api/portfolio"
  to = "/.netlify/functions/portfolio"
  status = 200

[[redirects]]
  from = "/api/transfers"
  to = "/.netlify/functions/transfers"
  status = 200

[[redirects]]
  from = "/api/admin/refresh-prices"
  to = "/.netlify/functions/admin-refresh-prices"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/init-demo"
  to = "/.netlify/functions/init-demo"
  status = 200

[[redirects]]
  from = "/api/admin/route"
  to = "/.netlify/functions/admin"
  status = 200

[[redirects]]
  from = "/api/admin/wallets"
  to = "/.netlify/functions/admin-wallets"
  status = 200

[[redirects]]
  from = "/api/admin/wallets/*"
  to = "/.netlify/functions/admin-wallets-detail/:splat"
  status = 200

[[redirects]]
  from = "/api/init-db"
  to = "/.netlify/functions/init-db"
  status = 200

# Handle Next.js static files and client-side routing properly
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/_next/image/*"
  to = "/_next/image/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/logo.svg"
  to = "/logo.svg"
  status = 200

# Handle client-side routing for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better caching and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Ensure proper MIME types for static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"

# Function configuration
[functions]
  directory = "netlify/functions"
  included_files = ["prisma/schema.prisma", "db/**/*"]

# Specific function configuration
[functions."*"]
  external_node_modules = ["@prisma/client"]
  timeout = 30
  node_bundler = "esbuild"