[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Production environment variables (these should be set in Netlify dashboard)
# [context.production.environment]
#   DATABASE_URL = "postgresql://username:password@host.neon.tech/dbname?sslmode=require"

# Redirect rules for API routes to serverless functions
[[redirects]]
  from = "/api/wallet"
  to = "/.netlify/functions/wallet"
  status = 200

[[redirects]]
  from = "/api/admin/inject"
  to = "/.netlify/functions/admin-inject"
  status = 200

[[redirects]]
  from = "/api/trending"
  to = "/.netlify/functions/trending"
  status = 200

# Handle other API routes with a catch-all function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Handle Next.js static files and client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better caching and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Function configuration
[functions]
  directory = "netlify/functions"
  included_files = ["prisma/schema.prisma", "db/**/*"]

# Specific function configuration
[functions."*"]
  external_node_modules = ["@prisma/client", "prisma", "next", "react", "react-dom"]
  timeout = 30
  node_bundler = "esbuild"